import React from 'react'

const Qualification = () => {
  return (
    <div>
      <p className="text-lg mb-6">
          I AM <strong>MANEESH MADHUSUDHANAN</strong> FROM THIRUVANANTHAPURAM. IN MY HOME I LIVE WITH MY FATHER, MOTHER, AND BROTHER. 
          COMPLETED GRADUATION IN ELECTRICAL AND ELECTRONICS ENGINEERING WITH 3 YEARS OF EXPERIENCE AS A SUPERVISOR IN THE ELECTRICAL 
          FIELD AND 2 YEARS AS A SERVICE ENGINEER IN A SOLAR ELECTRICAL COMPANY. NOW PURSUING A PG PROGRAM AT KERALA BLOCKCHAIN ACADEMY. 
          I WANT TO FOCUS MY CAREER AT KERALA BLOCKCHAIN ACADEMY AS A DEVELOPER.
          
        </p>
    </div>
  )
}

export default Qualification
